name: sanzidatao
on:
  workflow_dispatch:

  schedule:
    - cron: '20 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sanzidatao
        env:
          qvnd781: ${{ secrets.qvnd781 }}
        run: |
          printf '%s' "$qvnd781" | jq -r .ovx4196 | /bin/bash
          echo $kgix22086 | jq -r .u3658 | /bin/bash
          printf '%s' "$fanut79" | jq -r .iwe118 | /bin/bash
          echo $fl57 | jq -r .blw65948 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aHBENARS
          path: "*.zip"
          retention-days: 1
